from enum import Enum


class Sentinel(str, Enum):
    NO_CAP = "NO_CAP"
    NO_NOTICE_REQUIRED = "NO_NOTICE_REQUIRED"
    UNVERIFIED_STATUTE = "UNVERIFIED_STATUTE"
    REQUIRES_ATTORNEY_REVIEW = "REQUIRES_ATTORNEY_REVIEW"
